#include <iostream>
#include <cstdlib>
#include <ctime>
#include <cstdlib>
using namespace std;
typedef long long ll;
 
void drawLine(int n,char c)
{
    for(int i=0; i<n; i++)
        cout << c;
    cout << endl ;
}
void rules()
{
    system("cls"); // to clear the screen 
    cout << endl << endl;
    drawLine(80,'-');
    cout << "\t\tPLEASE CHECK THE RULES OF THIS GAME\n";
    drawLine(80,'-');
    cout << "\t1. Choose any number between 1 to 5\n";
    cout << "\t2. If you win you will get 5 times of money you bet\n";
    cout << "\t3. If you bet on wrong number you will lose your betting amount\n\n";
    drawLine(80,'-');
}
 
int main()
{
    string playerName;
    ll amount; // hold player's balance amount.
    ll betAmount; 
    int guess;
    int dice; // hold the number generated by computer.
    char choice;
 
    srand(time(0)); // Use current time as seed for random generator  

    drawLine(60,'_');
    cout << "\n\n\n\t\tCASINO GUESSING GAME\n\n\n\n";
    drawLine(60,'_');
 
    cout << "\n\nPlease Enter Your Name : ";
    getline(cin, playerName); // to take input the names with spaces
 
    cout << "\n\nEnter Deposit amount to play game : Rs";
    cin >> amount;
    
    do
    {
        system("cls");
        rules();
        cout << "\n\nYour current balance is $ " << amount << "\n";
		
		// Get player's betting amount until he/she enters a valid 
		// amount , use of "do while" loop is best in this scenario
		// this loop will end if the betting amount is less than the 
		// remaining balance
        do
        {
            cout <<playerName<<", Enter how much money do you want to bet : Rs";
            cin >> betAmount;
            if(betAmount > amount)
                cout << "Your betting amount is more than your current balance\n"
                       <<"\nPlease Re-enter your betting amount\n ";
        }while(betAmount > amount);
 
		// Get the player's number to check if he/she wins or not.
        do
        {
            cout << "Guess the number to bet between 1 to 5 :";
            cin >> guess;
            if(guess <= 0 || guess > 5)
            {
                cout << "Please check the number again !! the number should be between 1 to 5 as per the Rules\n"
                    <<"\nPlease Re-enter your number\n ";
            }
        }while(guess <= 0 || guess > 5);
 
        dice = 1 + rand()%5; // Will hold the randomly generated integer between 1 and 5
    
        if(dice == guess)
        {
            cout<< "You guessed the correct number : "<<dice<<endl;
            cout << "\n\nGood Luck!! You won Rs." << betAmount * 5;
            amount += betAmount * 5;
        }
        else
        {
            cout << "\nOops ! The winning number was : " << dice <<endl;
            cout << "Better Luck Next Time !! You lost Rs "<< betAmount <<"\n";
            amount -= betAmount;
        }
 
        
        cout << "\n"<<playerName<<", You have Rs " << amount << "\n";
        if(amount == 0)
        {
            cout << "Sorry You have no money to play ";
            break;
        }
        cout << "\n\n-->Do you want to play again (y/n)? ";		
        cin >> choice;
    }while(choice =='Y'|| choice=='y');
    
    cout << "\n\n\n";
    drawLine(70,'=');
    cout << "\n\nThanks for playing this game. Your balance amount is Rs " << amount << " Mr. " <<playerName<<"\n\n";
    drawLine(70,'=');
 
    return 0;
}
 
